// Disable transactions for this migration
export const transaction = false;

export const up = async function(knex) {
  // The constraint name is generated by knex, typically <table>_<columns>_unique
  await knex.raw('ALTER TABLE daily_statuses DROP CONSTRAINT IF EXISTS daily_statuses_employee_id_project_id_date_unique');
};

export const down = async function(knex) {
  await knex.raw('ALTER TABLE daily_statuses ADD CONSTRAINT daily_statuses_employee_id_project_id_date_unique UNIQUE (employee_id, project_id, date)');
};
